### ISSUE TITLE
HUD variables (suggestion)

### ISSUE THREAD

**Issue by QaleQ** [hettoo/racesow#13]
I'd really like the variable connected to displaying times (%TIME_RECORD and %TIME_BEST) in the bottom right corner of the racesow hud, to have 3 decimals, if possible.

Also, if there's some way to add a variable that reads the current MGX rec, so I could add that in the bottom right corner aswell

**Comment by hettoo** [comment]
First part isn't possible, or at least not practical. The datatype used to store stats like this which are transmitted to the client has about 65k different values. To make sure high times fit they are rounded to one decimal. With three the highest representable time would be about one minute.
This is also why scores shown on websites are fucked up with high times.

**Comment by QaleQ** [comment]
allright, no biggie i suppose :> last part is possible tho, right?

**Comment by hettoo** [comment]
Added, as TIME_ALPHA. Looks like the racesow hud already shows that. Not sure what this does with normal huds, because it was hidden behind some unimplemented function which should determine if you are using the racesow client.
I'll hear about it if it causes any problems.
