### ISSUE TITLE
Noclip (suggestion)

### ISSUE THREAD

**Issue by QaleQ** [hettoo/racesow#14]
If it's possible, it would be great if the racerestart command kept you being in noclip if you used the cmd while currently in noclip. So that if you want to slightly alter your /position save location, you could go into noclip at any time, racerestart to get to your previous /position save, alter position slightly, then save position again.

**Comment by hettoo** [comment]
/position load should be doing just that at the moment.
IMO this is the desired behavior, because in situations other than finding a good position in the air, players generally want to loose the noclip property when pressing the restart button.

**Comment by QaleQ** [comment]
this way you would get all the functionality from just a noclip bind and a kill bind.
and from what i can tell it seems that nobody has thought about making a position load bind so that they can teleport, instead of die and start with speed, when in noclip. going out of noclip before you spawn to get the effect of position speed is really not that big a hassle, is it? :p

**Comment by hettoo** [comment]
kk :p

**Comment by QaleQ** [comment]
"kk" as in "doing it", or "kk" as in "fu"? :P

**Comment by hettoo** [comment]
As in "done it" ;)
https://github.com/hettoo/racesow/commit/4beef6d564bfcc73fd3adf50e79c39c1bd92b6f6

**Comment by QaleQ** [comment]
cool, just tried it and it feels vn :)
though, would it be possible to not have position speed affect you when spawning in noclip?

**Comment by hettoo** [comment]
Forgot that, done.
