### ISSUE TITLE
H bot player name (suggestion)

### ISSUE THREAD

**Issue by QaleQ** [hettoo/racesow#16]
Not sure if you got a seperate github repo for the H bot, but in any case; The replies from the H bot is so instantaneous that very often the noob don't realize it's a reply to his question. Perhaps you could incorporate the nickname of the person H bot is replying to in the message, alternatively add like a 1s delay before responding.

**Comment by hettoo** [comment]
Done.
chatsow repo can be found here: https://github.com/hettoo/chatsow
