### ISSUE TITLE
chase score

### ISSUE THREAD

**Issue by QaleQ** [hettoo/racesow#17]
Chase score still acting up, this time it prioritized a player with no time before a player with a time set.

**Comment by hettoo** [comment]
Accidentally removed that zero exception code, should get fixed now. :p

**Comment by QaleQ** [comment]
chase score'd right after you left on southrun, leading to a major glitch where it kept flickering between a guy with no time set and the guy it's acctually supposed to chase!

**Comment by hettoo** [comment]
lol

**Comment by hettoo** [comment]
Guess I got it now. :p
