### ISSUE TITLE
Privsay colors (or something)

### ISSUE THREAD

**Issue by QaleQ** [hettoo/racesow#18]
I was thinking, maybe the (Private message to/from < playername >) messages could have different colors for sent and recieved messages. Maybe something as simple as only coloring the words to and from differently, or change the color of the entire row of text. 
Can get confusing with the only difference from a sent and a recieved message is that small red "from/to" word (apart from the contents of the msg ofcourse x>)

**Comment by QaleQ** [comment]
and maybe, while your messing around that code, you could remove the two unnecessary spaces that come right after the playername, making it
(Private message to/from < playername >): < message >
instead of
(Private message to/from < playername > ) : < message >

**Comment by hettoo** [comment]
Sure, although over-using colors gets messy and the output of this command is already bloated too.
In some mod I worked on for a while I just had name >>>/<<< message. Maybe this way the direction of the arrows would be clear enough to easily make the distinction?

**Comment by QaleQ** [comment]
That's true. What you proposed looked much sleeker and clearer :)
