### ISSUE TITLE
Diffref parameters (suggestion)

### ISSUE THREAD

**Issue by QaleQ** [hettoo/racesow#9]
Would be nice if everyone stuck to being consistent with the terms used to describe record type: personal/server/mgx.
could diffref perhaps get changed from self/server/world to personal/server/mgx?
Also, what purpouse does the "auto" parameter really fill? from what i can tell it always uses server cp's when you use that..

**Comment by hettoo** [comment]
Renamed self to personal.
MGX is the identifier for the database, the name is a setting. Having this as an option may be inconvenient. For example, the name might be long or contain spaces.

Auto is the default behavior: server for cps and personal for finish.

**Comment by QaleQ** [comment]
allright, fair enought :p perhaps we could think about changing where it says "MGX" to "world" in other places, to make things clearer. not high priority though!

**Comment by hettoo** [comment]
Having such a name and showing it is a good thing, it just shouldn't be something players need to type for certain functionality.

**Comment by QaleQ** [comment]
i guess i see your point
